apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: "master"
  tasks:
    # 1. CLEANUP TASK (Runs first)
    - name: cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    # 2. CLONE TASK (Runs after cleanup)
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      runAfter:
        - cleanup  # This ensures it waits for cleanup to finish
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)