apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: app-name
    - name: repo-url
    - name: branch
      default: "master"
    - name: build-image
  tasks:
    # 1. CLEANUP TASK
    - name: cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    # 2. CLONE TASK
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)

    # 3. ESLINT TASK (FIXED)
    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: eslint
      runAfter:
        - clone
    
    # 4.JEST task 
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: jest
      params:
      - name: args
        value: "--verbose --coverage"
      runAfter:
        - lint

    # 5.building an image
    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: "$(params.build-image)"
      runAfter:
        - tests

    # 6.Deploying in openshift-cluster
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
      - name: SCRIPT
        value: |
          # Check if deployment exists
          if oc get deploy $(params.app-name); then
            echo "Deployment exists. Updating image..."
            oc set image deploy/$(params.app-name) $(params.app-name)=$(params.build-image)
          else
            echo "Deployment does not exist. Creating..."
            oc create deploy $(params.app-name) --image=$(params.build-image)
          fi
      runAfter:
        - build
        