apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: "master"
  tasks:
    # 1. CLEANUP TASK
    - name: cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    # 2. CLONE TASK
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)

    # 3. ESLINT TASK (FIXED)
    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: eslint
      runAfter:
        - clone