apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone      
spec:
  workspaces:           
    - name: output
      description: The git repo will be cloned onto this volume
  params:
    - name: url         
      description: The URL of the git repo to clone
      type: string
    - name: revision    
      description: The branch to clone
      type: string
      default: master
  steps:
    - name: clone
      image: bitnami/git:latest
      workingDir: $(workspaces.output.path) 
      script: |
        # Clone into the current directory (workspace)
        # We use '.' because workingDir is set to the workspace path
        git clone --branch $(params.revision) $(params.url) .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: output
  steps:
    - name: clean
      image: alpine:3.12
      workingDir: $(workspaces.output.path)
      script: |
        echo "Cleaning up workspace..."
        rm -rf ./*
        rm -rf .[^.]* # Removes hidden files like .git
        echo "Successfully cleaned workspace."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  steps:
    - name: install-dependencies
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
    - name: run-eslint
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npx eslint .