apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: master
  steps:
    - name: clone
      image: bitnami/git:latest
      workingDir: $(workspaces.output.path)
      script: |
        git clone --branch $(params.revision) $(params.url) .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: output
  steps:
    - name: clean
      image: alpine:3.12
      workingDir: $(workspaces.output.path)
      script: |
        echo "Cleaning up workspace..."
        rm -rf ./*
        rm -rf .[^.]*
        echo "Successfully cleaned workspace."

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        # Install dependencies
        npm ci
        
        # Run the lint script defined in package.json
        npm run lint