apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone      
spec:
  workspaces:           
    - name: output
      description: The git repo will be cloned onto this volume
  params:
    - name: url         
      description: The URL of the git repo to clone
      type: string
    - name: revision    
      description: The branch to clone
      type: string
      default: master
  steps:
    - name: clone
      image: bitnami/git:latest
      workingDir: $(workspaces.output.path) 
      script: |
        # Clone into the current directory (workspace)
        # We use '.' because workingDir is set to the workspace path
        git clone --branch $(params.revision) $(params.url) .