apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
    - name: repository
      description: The git repo
      default: " "
    - name: branch
      description: the branch for the git repo
      default: master
    # Added app-name so you can pass it to the pipeline
    - name: app-name 
      description: The name of the application
      default: "tekton-lab" 
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cd-pipeline-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: cd-pipeline
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipelinerun-pvc
        params:
          - name: repo-url
            value: $(tt.params.repository)
          - name: branch
            value: $(tt.params.branch)
          - name: app-name
            value: $(tt.params.app-name)
          # FIX: Construct the full image URL using the current namespace
          - name: build-image
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(tt.params.app-name):latest